:FOR_SIGHT
@ECHO OFF&&CLS&&CALL:PAD_LINE
ECHO  FOR~SIGHT - WANNA ARGUE?&&CALL:PAD_LINE
IF NOT DEFINED FOR_SAV SET "FOR_SAV=FRESH"&&SET "CLM_TGT=1"&&SET "CMD_MODE=INT"&&SET "GET_ROW=1"
IF EXIST EXT.CMD SET /P CUR_CMD=<EXT.CMD
IF NOT DEFINED CUR_CMD SET "CUR_CMD=VER"
IF DEFINED CUR_CMD %CUR_CMD% >$FOR
SET "ROW="&&IF EXIST "$FOR" FOR /F "TOKENS=1-9 DELIMS=<>()" %%A IN ($FOR) DO (SET "ARGUE=%%A%%B%%C%%D%%E%%F%%G%%H"&&CALL:ARGUE)
IF EXIST "$FOR" SET "MARK="&&DEL /F $FOR>NUL 2>&1
IF DEFINED FS_LAST ECHO  {FOR} %FS_LAST%
CALL:PAD_LINE&&ECHO  {T}CLM[%CLM_TGT%] {F}ull  {R}ef          {G}o  {V}iew  {M}ode[%FOR_SAV%]  {Q}uit&&CALL:PAD_LINE
ECHO  {D}ELIMS[%DELIMS%]  {C}MD [%CUR_CMD%]&&CALL:PAD_LINE
ECHO                  Press (Enter) to reparse FOR results&&CALL:MENU_SELECT
IF "%SELECT%"=="Q" EXIT /B
IF "%SELECT%"=="G" START CMD /C FOR.CMD
IF "%SELECT%"=="V" START NOTEPAD.EXE FOR.CMD
IF "%SELECT%"=="T" IF NOT DEFINED ROW_EXT SET "SELECT="&&SET /A "CLM_TGT+=1"&&IF "%CLM_TGT%"=="9" SET "CLM_TGT=1"
IF "%SELECT%"=="T" IF DEFINED ROW_EXT SET "SELECT="&&SET /A "CLM_TGT+=1"&&IF "%CLM_TGT%"=="20" SET "CLM_TGT=1"
IF "%SELECT%"=="M" IF "%FOR_SAV%"=="FRESH" SET "FOR_SAV=REUSE"&&SET "SELECT="&&GOTO:FOR_SIGHT
IF "%SELECT%"=="M" IF "%FOR_SAV%"=="REUSE" SET "FOR_SAV=FRESH"&&SET "SELECT="&&GOTO:FOR_SIGHT
IF "%SELECT%"=="F" IF NOT DEFINED ROW_EXT SET "ROW_EXT=1"&&SET "SELECT="&&GOTO:FOR_SIGHT
IF "%SELECT%"=="F" IF DEFINED ROW_EXT SET "ROW_EXT="&&SET "SELECT="&&SET "CLM_TGT=1"&&GOTO:FOR_SIGHT
IF "%SELECT%"=="R" IF NOT DEFINED FOR_REF SET "FOR_REF=1"&&SET "SELECT="&&GOTO:FOR_SIGHT
IF "%SELECT%"=="R" IF DEFINED FOR_REF SET "FOR_REF="&&SET "SELECT="&&GOTO:FOR_SIGHT
IF "%SELECT%"=="C" IF NOT EXIST EXT.CMD ECHO;VER.EXE>EXT.CMD
IF "%SELECT%"=="C" SET "SELECT="&&CALL:PAD_LINE&&START NOTEPAD.EXE EXT.CMD&&GOTO:FOR_SIGHT
IF "%SELECT%"=="D" SET SELECT=&&SET "PROMPT_SET=DELIMS"&&CALL:PROMPT_SET_ANY
IF "%SELECT%" GTR "0" SET "SKIP_CNT=%SELECT%"&&SET "ROW_TGT=%SELECT%"
IF "%SELECT%" GTR "0" SET "MARK=1"&&SET /A "SKIP_CNT-=1"
IF "%SELECT%" GTR "0" CALL SET "SKIPPER=SKIP=%SKIP_CNT%"
IF "%SELECT%"=="1" SET "SKIPPER="
GOTO:FOR_SIGHT
:PAD_LINE
ECHO =======================================================================
EXIT /B
:PROMPT_SET_ANY
SET "PROMPT_VAR="&&SET /P "PROMPT_VAR=$>>"
CALL SET "%PROMPT_SET%=%PROMPT_VAR%"&&SET "PROMPT_SET="&&SET "PROMPT_VAR="
EXIT /B
:MENU_SELECT
REM MENU_SELECT_MENU_SELECT_MENU_SELECT_MENU_SELECT_MENU_SELECT
SET "SELECT="&&SET /P "SELECT=$>>"&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (CALL SET "SELECT=%%SELECT:%%G=%%G%%")
EXIT /B
:ARGUE
IF NOT DEFINED ARGUE EXIT /B
IF NOT DEFINED DELIMS SET "DELIMS= "
IF DEFINED FOR_REF FOR /F "TOKENS=1-9 DELIMS=<>()" %%A IN ("%ARGUE%") DO (CALL SET "ARGUE=%%A%%B%%C%%D%%E%%F%%G"&&CALL ECHO *REF* [%%A])
FOR %%1 in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20) DO (CALL SET "C%%1="&&CALL SET "A%%1=")
SET "C="&&IF NOT "%DELIMS%"==" " FOR /F "DELIMS=" %%G IN ('CMD.EXE /D /U /C ECHO %DELIMS%^| FIND /V ""') do (CALL SET /A "C+=1"&&SET "V=%%G"&&CALL:DELIMS)
SET "X="&&SET "A=1"&&FOR /F "DELIMS=" %%1 in ('CMD.EXE /D /U /C ECHO %ARGUE%^| FIND /V ""') DO (CALL SET "V=%%1"&&CALL:ARGUEX)
CALL SET /A "ROW+=1"&&IF DEFINED ARG_ONE CALL:ARG_SHIFT
IF DEFINED GET_ROW IF DEFINED ROW_EXT IF "%ROW%"=="%ROW_TGT%" CALL SET "ROW_DSP={1A{%A1%}-{2B{%A2%}-{3C{%A3%}-{4D{%A4%}-{5E{%A5%}-{6F{%A6%}-{7G{%A7%}-{8H{%A8%}-{9I{%A9%}-{10J{%A10%}-{11K{%A11%}-{12L{%A12%}-{13M{%A13%}-{14N{%A14%}-{15O{%A15%}-{16P{%A16%}-{17Q{%A17%}-{18R{%A18%}-{19S{%A19%}-{20T{%A20%}"
IF DEFINED GET_ROW IF DEFINED ROW_EXT IF DEFINED ROW CALL ECHO  {%ROW%} {1A{%A1%}-{2B{%A2%}-{3C{%A3%}-{4D{%A4%}-{5E{%A5%}-{6F{%A6%}-{7G{%A7%}-{8H{%A8%}-{9I{%A9%}-{10J{%A10%}-{11K{%A11%}-{12L{%A12%}-{13M{%A13%}-{14N{%A14%}-{15O{%A15%}-{16P{%A16%}-{17Q{%A17%}-{18R{%A18%}-{19S{%A19%}-{20T{%A20%}&&CALL:PAD_LINE
IF DEFINED GET_ROW IF NOT DEFINED ROW_EXT IF "%ROW%"=="%ROW_TGT%" CALL SET "ROW_DSP={1A{%A1%}-{2B{%A2%}-{3C{%A3%}-{4D{%A4%}-{5E{%A5%}-{6F{%A6%}-{7G{%A7%}-{8H{%A8%}-{9I{%A9%}"
IF DEFINED GET_ROW IF NOT DEFINED ROW_EXT IF DEFINED ROW CALL ECHO  {%ROW%} {1A{%A1%}-{2B{%A2%}-{3C{%A3%}-{4D{%A4%}-{5E{%A5%}-{6F{%A6%}-{7G{%A7%}-{8H{%A8%}-{9I{%A9%}&&CALL:PAD_LINE
IF DEFINED MARK IF "%ROW%"=="%ROW_TGT%" IF "%FOR_SAV%"=="FRESH" IF EXIST FOR.CMD DEL /F FOR.CMD>NUL
IF DEFINED MARK IF "%ROW%"=="%ROW_TGT%" CALL SET CLM_DAT=%%A%CLM_TGT%%%&&IF NOT EXIST FOR.CMD ECHO @ECHO OFF>FOR.CMD
IF DEFINED MARK IF "%ROW%"=="%ROW_TGT%" CALL SET FS_LAST=[SKIP[%SKIPPER%] [DELIM[%DELIMS%] [IN[CMD] [IF[%%%%%CLM_TGT%]==[%CLM_DAT%]
IF DEFINED MARK IF "%ROW%"=="%ROW_TGT%" ECHO FOR /F "TOKENS=1-9 %SKIPPER% DELIMS=<>()%DELIMS%" %%%%1 IN ('%CUR_CMD%') DO (IF "%%%%%CLM_TGT%"=="%CLM_DAT%" ECHO [%CLM_DAT%] FOUND^&PAUSE)>>FOR.CMD
SET "ARGUE="&&SET "ARG_ONE="&&EXIT /B
:DELIMS
CALL SET "C%C%=%V%"&&EXIT /B
:ARGUEX
IF "%DELIMS%"==" " SET "C1= "
IF "%V%"=="%C1%" IF DEFINED X IF DEFINED C1 CALL SET "A%A%=%X%"&&CALL SET /A "A+=1"&&CALL SET "X="
IF "%V%"=="%C2%" IF DEFINED X IF DEFINED C2 CALL SET "A%A%=%X%"&&CALL SET /A "A+=1"&&CALL SET "X="
IF "%V%"=="%C3%" IF DEFINED X IF DEFINED C3 CALL SET "A%A%=%X%"&&CALL SET /A "A+=1"&&CALL SET "X="
IF "%V%"=="%C4%" IF DEFINED X IF DEFINED C4 CALL SET "A%A%=%X%"&&CALL SET /A "A+=1"&&CALL SET "X="
IF "%V%"=="%C5%" IF DEFINED X IF DEFINED C5 CALL SET "A%A%=%X%"&&CALL SET /A "A+=1"&&CALL SET "X="
IF NOT "%V%"=="%C1%" IF NOT "%V%"=="%C2%" IF NOT "%V%"=="%C3%" IF NOT "%V%"=="%C4%" IF NOT "%V%"=="%C5%" CALL SET "X=%X%%V%"
IF DEFINED X SET "A%A%=%X%"
EXIT /B

